os:
 - linux
 - osx
language: c
compiler:
 - clang
 - gcc
before_install:
 # we need a more recent cmake than travis/linux provides (at least 2.8.9):
 - |
     if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]
     then
         echo 'yes' | sudo add-apt-repository ppa:kalakris/cmake
         sudo apt-get update -qq
         sudo apt-get install -qq cmake python3 valgrind
     elif [ ${TRAVIS_OS_NAME:-'linux'} = 'osx' ]
     then
         echo "Building without python3, to make sure that works."
     fi
script:
 - make
 - make test
 - |
     if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]
     then
         make leakcheck
     fi
